import = [ "~/.config/alacritty/catppuccin-mocha.toml" ]

[font]
size = 12.0

[font.normal]
family = "FiraCode Nerd Font"

[selection]
save_to_clipboard = true

[shell]
args = ["--login"]
program = "/bin/zsh"

[window]
startup_mode = "Maximized"
option_as_alt = "Both"
